#!/bin/bash

# Instalando fonts
echo "Instalando fonts"
mkdir ~/.fonts
cp ./mononoki/* ~/.fonts

echo "Instalando tema"
code --install-extensions wesbos.theme-cobalt2

# Move settings file to user config
echo "Movendo configuração do editor"
cp ./settings.json ~/.config/Code/User

# Instalando extenções
./extensions

echo "Pronto."
sleep 1
