#!/bin/bash

# Instalando fonts e temas
echo "Instalando fonts"
mkdir ~/.fonts
cp ./mononoki/* ~/.fonts
cp ./operator-mono/* ~/.fonts

# Instalando icons e temas
echo "Instalando icons e temas"
code --install-extension emmanuelbeziat.vscode-great-icons

# Instalando extenções
./extensions

# Move settings file to user config
echo "Movendo configuração do editor"
cp ./settings.json ~/.config/Code/User

echo "Pronto."
sleep 1
